name: "Update casks"
on:
  push:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    name: "Update casks"
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: "Install updater"
        run: pip3 install .

      - uses: actions/checkout@v5
        with:
          ref: data

      - name: "Update casks"
        run: |
          rm -rf packages README.md
          nix-homebrew-casks

      - uses: EndBug/add-and-commit@v9
        with: { default_author: github_actions }
